### Mathematics with Numpy

In [1]:
import numpy as np

In [2]:
x = np.random.randn(3,4)
x

array([[-0.06638332,  0.13241295,  0.46124845, -0.836314  ],
       [ 0.51827005,  0.09203277, -1.65001028,  0.27776202],
       [-1.9166289 ,  0.71446715,  0.62035981, -0.65647725]])

In [3]:
np.sum(x) # sum all elements

-2.309260545868226

In [4]:
np.sum(x, 0) # sum columns, 4 elements

array([-1.46474217,  0.93891287, -0.56840202, -1.21502923])

In [5]:
np.cumsum(x,0) # cumulative sum of columns

array([[-0.06638332,  0.13241295,  0.46124845, -0.836314  ],
       [ 0.45188673,  0.22444572, -1.18876183, -0.55855198],
       [-1.46474217,  0.93891287, -0.56840202, -1.21502923]])

In [6]:
np.sum(x, 1) # sum rows, 3 elements

array([-0.30903592, -0.76194544, -1.23827919])

In [7]:
np.cumsum(x, 1) # cumulative sum of rows

array([[-0.06638332,  0.06602963,  0.52727808, -0.30903592],
       [ 0.51827005,  0.61030283, -1.03970745, -0.76194544],
       [-1.9166289 , -1.20216175, -0.58180194, -1.23827919]])

In [8]:
np.diff(x) # Same as diff(x, axis=1)

array([[ 0.19879627,  0.3288355 , -1.29756245],
       [-0.42623728, -1.74204305,  1.9277723 ],
       [ 2.63109605, -0.09410734, -1.27683705]])

In [9]:
np.diff(x, axis=0)

array([[ 0.58465338, -0.04038018, -2.11125873,  1.11407601],
       [-2.43489896,  0.62243438,  2.27037009, -0.93423926]])