### List Comprehensions

In [1]:
import numpy as np

In [2]:
x = np.arange(5.0)
x

array([0., 1., 2., 3., 4.])

In [3]:
y = []
y

[]

In [4]:
for i in range(len(x)):
    y.append(np.exp(x[i]))
y

[1.0,
 2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236]

In [5]:
z = [np.exp(x[i]) for i in range(len(x))]
z

[1.0,
 2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236]

In [6]:
x = np.arange(5.0)
x

array([0., 1., 2., 3., 4.])

In [7]:
y = []
y

[]

In [8]:
for i in range(len(x)):
    if np.floor(i/2)==i/2:
        y.append(x[i]**2)
y

[0.0, 4.0, 16.0]

In [9]:
z = [x[i]**2 for i in range(len(x)) if np.floor(i/2)==i/2]
z

[0.0, 4.0, 16.0]

In [10]:
x1 = np.arange(5.0)
x1

array([0., 1., 2., 3., 4.])

In [11]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [12]:
y = []
y

[]

In [13]:
for i in range(len(x1)):
    for j in range(len(x2)):
        y.append(x1[i]*x2[j])
y

[0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 2.0, 4.0, 0.0, 3.0, 6.0, 0.0, 4.0, 8.0]

In [14]:
z = [x1[i]*x2[j] for i in range(len(x1)) for j in range(len(x2))]
z

[0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 2.0, 4.0, 0.0, 3.0, 6.0, 0.0, 4.0, 8.0]

In [15]:
# Only when i==j
z = [x1[i]*x2[j] for i in range(len(x1)) for j in range(len(x2)) if i==j]
z

[0.0, 1.0, 4.0]

In [16]:
x = np.arange(-5.0,5.0)
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [17]:
len(x)

10

In [18]:
range(len(x))

range(0, 10)

In [19]:
z_set = {x[i]**2.0 for i in range(len(x))}
z_set

{0.0, 1.0, 4.0, 9.0, 16.0, 25.0}

In [20]:
z_dict = {i:np.exp(i) for i in x}
z_dict

{-5.0: 0.006737946999085467,
 -4.0: 0.01831563888873418,
 -3.0: 0.049787068367863944,
 -2.0: 0.1353352832366127,
 -1.0: 0.36787944117144233,
 0.0: 1.0,
 1.0: 2.718281828459045,
 2.0: 7.38905609893065,
 3.0: 20.085536923187668,
 4.0: 54.598150033144236}

In [21]:
z_tuple = tuple(i**3 for i in x)
z_tuple

(-125.0, -64.0, -27.0, -8.0, -1.0, 0.0, 1.0, 8.0, 27.0, 64.0)