### Solve Arrays

In [1]:
import numpy as np

In [2]:
X = np.array([[1.0,2.0,3.0],[3.0,3.0,4.0],[1.0,1.0,4.0]])
X

array([[1., 2., 3.],
       [3., 3., 4.],
       [1., 1., 4.]])

In [3]:
y = np.array([[1.0],[2.0],[3.0]])
y

array([[1.],
       [2.],
       [3.]])

In [4]:
np.linalg.solve(X,y)

array([[ 0.625],
       [-1.125],
       [ 0.875]])

In [5]:
X = np.random.randn(100,2)

In [6]:
y = np.random.randn(100)

In [7]:
np.linalg.lstsq(X,y)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([0.07564831, 0.01345671]),
 array([104.54486262]),
 2,
 array([11.27549587,  9.73202655]))