### Shape and Transform Arrays

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
x * x # Element-by-element multiplication

array([[ 1,  4],
       [ 9, 16]])

In [4]:
np.mat(x) * np.mat(x) # Matrix multiplication

matrix([[ 7, 10],
        [15, 22]])

### shape

In [5]:
x = np.random.randn(4,3)
x

array([[-1.6805029 ,  0.2201249 , -1.10294856],
       [ 0.619043  , -1.26874087, -0.41404593],
       [-0.43151322, -1.14178928, -0.35088592],
       [ 1.42068202, -0.99177388, -1.33309056]])

In [6]:
x.shape

(4, 3)

In [7]:
np.shape(x)

(4, 3)

In [8]:
M,N = np.shape(x)

In [9]:
x.shape = N,M
x

array([[-1.6805029 ,  0.2201249 , -1.10294856,  0.619043  ],
       [-1.26874087, -0.41404593, -0.43151322, -1.14178928],
       [-0.35088592,  1.42068202, -0.99177388, -1.33309056]])

In [10]:
x.shape = 6,-1
x

array([[-1.6805029 ,  0.2201249 ],
       [-1.10294856,  0.619043  ],
       [-1.26874087, -0.41404593],
       [-0.43151322, -1.14178928],
       [-0.35088592,  1.42068202],
       [-0.99177388, -1.33309056]])

### reshape

In [11]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
y = np.reshape(x,(4,1)) # Reshape to vector
y

array([[1],
       [2],
       [3],
       [4]])

In [13]:
z = np.reshape(y,(1,4))
z

array([[1, 2, 3, 4]])

In [14]:
w = np.reshape(z,(2,2))
w

array([[1, 2],
       [3, 4]])

### size

In [15]:
x = np.random.randn(4,3)
x

array([[ 0.15197133, -1.2013386 ,  1.63385749],
       [ 0.14932498,  1.55795814,  1.85068731],
       [ 1.30179592, -0.27890168,  0.44047348],
       [-0.86719826, -1.26415526, -0.47298724]])

In [16]:
np.size(x)

12

In [17]:
x.size

12

### dimensions

In [18]:
x = np.random.randn(4,3)
x

array([[ 0.10036405, -0.29826742, -0.36309344],
       [-2.12030654, -1.45527818,  0.79637943],
       [-1.07861737,  2.22162632, -0.7787927 ],
       [-0.80676626, -0.10748226, -0.95275335]])

In [19]:
np.ndim(x)

2

In [20]:
x.ndim

2

### tile

In [21]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [22]:
z = np.hstack((x,x,x))
z

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [23]:
y = np.vstack((z,z))
y

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [24]:
w = np.tile(x,(2,3))
w

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [25]:
y - w

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### ravel

In [26]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
x.ravel()

array([1, 2, 3, 4])

In [28]:
x.T.ravel()

array([1, 3, 2, 4])

### flat

In [29]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
x.flat

In [31]:
x.flat[2]

3

In [32]:
x.flat[1:4] = -1
x

array([[ 1, -1],
       [-1, -1]])

### broadcast

In [33]:
x = np.array([[1,2,3,4]])
x

array([[1, 2, 3, 4]])

In [34]:
y = np.reshape(x,(4,1))
y

array([[1],
       [2],
       [3],
       [4]])

In [35]:
b = np.broadcast(x,y)
b.shape

(4, 4)

In [36]:
for u,v in b:
    print('x: ', u, ' y: ',v)

x:  1  y:  1
x:  2  y:  1
x:  3  y:  1
x:  4  y:  1
x:  1  y:  2
x:  2  y:  2
x:  3  y:  2
x:  4  y:  2
x:  1  y:  3
x:  2  y:  3
x:  3  y:  3
x:  4  y:  3
x:  1  y:  4
x:  2  y:  4
x:  3  y:  4
x:  4  y:  4


In [37]:
b = np.broadcast_arrays(x,y)
b

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]), array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])]

In [38]:
b[0]

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [39]:
b[1]

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

### vstack, hstack

In [40]:
x = np.reshape(np.arange(6),(2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
y = x

In [42]:
np.vstack((x,y))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [43]:
np.hstack((x,y))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### split, vsplit, hsplit

In [44]:
x = np.reshape(np.arange(20),(4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
y = np.vsplit(x,2)
y

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [46]:
y = np.hsplit(x,[1,3])
y

[array([[ 0],
        [ 5],
        [10],
        [15]]), array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

### delete

In [47]:
x = np.reshape(np.arange(20),(4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
np.delete(x,1,0) # Same as x[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
np.delete(x,[2,3],1) # Same as x[:,[0,1,4]]

array([[ 0,  1,  4],
       [ 5,  6,  9],
       [10, 11, 14],
       [15, 16, 19]])

In [50]:
np.delete(x,[2,3]) # Same as hstack((x.flat[:2],x.flat[4:]))

array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

### squeeze

In [51]:
x = np.ones((5,1,5,1))
x

array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]])

In [52]:
y = x.squeeze()
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
y = np.squeeze(x)
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### fliplr, flipud

In [54]:
x = np.reshape(np.arange(4),(2,2))
x

array([[0, 1],
       [2, 3]])

In [55]:
np.fliplr(x)

array([[1, 0],
       [3, 2]])

In [56]:
np.flipud(x)

array([[2, 3],
       [0, 1]])

### diag

In [57]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [58]:
y = np.diag(x)
y

array([1, 4])

In [59]:
z = np.diag(y)
z

array([[1, 0],
       [0, 4]])

### triu, tril

In [60]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [61]:
np.triu(x)

array([[1, 2],
       [0, 4]])

In [62]:
np.tril(x)

array([[1, 0],
       [3, 4]])