### Import and Export Data

In [1]:
from pandas import read_csv

In [2]:
csv_data = read_csv('FTSE_2012.csv',
                    header=None,
                    index_col=False)

In [3]:
csv_data

0       1       2       3       4          5       6
0  2/15/12  5899.9  5923.8  5880.6  5892.2  801550000  5892.2
1  2/14/12  5905.7  5920.6  5877.2  5899.9  832567200  5899.9
2  2/13/12  5852.4  5920.1  5852.4  5905.7  643543000  5905.7
3  2/10/12  5895.5  5895.5  5839.9  5852.4  948790200  5852.4

In [4]:
from pandas import read_excel

In [5]:
excel_data = read_excel('FTSE_2012.xlsx','Sheet1',
                        header=None,
                        index_col=False)

In [6]:
excel_data

0       1       2       3       4          5       6
0 2012-02-15  5899.9  5923.8  5880.6  5892.2  801550000  5892.2
1 2012-02-14  5905.7  5920.6  5877.2  5899.9  832567200  5899.9
2 2012-02-13  5852.4  5920.1  5852.4  5905.7  643543000  5905.7
3 2012-02-10  5895.5  5895.5  5839.9  5852.4  948790200  5852.4

In [7]:
import xlrd

In [8]:
wb = xlrd.open_workbook('FTSE_2012.xlsx')

In [9]:
wb

In [10]:
sheetNames = wb.sheet_names()

In [11]:
sheet = wb.sheet_by_name(sheetNames[0])

In [12]:
excelData = [] # List to hold data
for i in range(sheet.nrows):
    excelData.append(sheet.row_values(i))

In [13]:
excelData

[[40954.0, 5899.9, 5923.8, 5880.6, 5892.2, 801550000.0, 5892.2],
 [40953.0, 5905.7, 5920.6, 5877.2, 5899.9, 832567200.0, 5899.9],
 [40952.0, 5852.4, 5920.1, 5852.4, 5905.7, 643543000.0, 5905.7],
 [40949.0, 5895.5, 5895.5, 5839.9, 5852.4, 948790200.0, 5852.4]]

In [14]:
import openpyxl

In [15]:
wb = openpyxl.load_workbook('FTSE_2012.xlsx')

In [16]:
wb

In [17]:
sheetNames = wb.sheetnames

In [18]:
sheet = wb[sheetNames[0]]

In [19]:
rows = sheet.rows

In [20]:
rows

<generator object Worksheet._cells_by_row at 0x11615af48>

In [21]:
open_price = [row[1].value for row in rows]

In [22]:
open_price

[5899.9, 5905.7, 5852.4, 5895.5]

### save and export data

In [23]:
import numpy as np

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y = np.zeros((10,10))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.savez_compressed('test',x,y)

In [27]:
data = np.load('test.npz')

In [28]:
x = data['arr_0']
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
y = data['arr_1']
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.savez_compressed('test', x=x, y=y)

In [31]:
data = np.load('test.npz')

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
x = np.random.randn(10)
x

array([-0.37087914,  0.40333662, -0.21157038, -0.05484298, -1.79300989,
        0.80461421,  0.27874258,  0.00926485,  2.42702199,  0.26969687])

In [35]:
np.savetxt('commas.csv', x, delimiter=',')

In [36]:
xData = np.loadtxt('commas.csv', delimiter=',')

In [37]:
xData

array([-0.37087914,  0.40333662, -0.21157038, -0.05484298, -1.79300989,
        0.80461421,  0.27874258,  0.00926485,  2.42702199,  0.26969687])