### Import and Export Data

In [12]:
from pandas import read_csv

In [13]:
csv_data = read_csv('FTSE_2012.csv',
                    header=None,
                    index_col=False)

In [14]:
csv_data

0       1       2       3       4          5       6
0  2/15/12  5899.9  5923.8  5880.6  5892.2  801550000  5892.2
1  2/14/12  5905.7  5920.6  5877.2  5899.9  832567200  5899.9
2  2/13/12  5852.4  5920.1  5852.4  5905.7  643543000  5905.7
3  2/10/12  5895.5  5895.5  5839.9  5852.4  948790200  5852.4

In [15]:
from pandas import read_excel

In [20]:
excel_data = read_excel('FTSE_2012.xlsx','Sheet1',
                        header=None,
                        index_col=False)

In [21]:
excel_data

0       1       2       3       4          5       6
0 2012-02-15  5899.9  5923.8  5880.6  5892.2  801550000  5892.2
1 2012-02-14  5905.7  5920.6  5877.2  5899.9  832567200  5899.9
2 2012-02-13  5852.4  5920.1  5852.4  5905.7  643543000  5905.7
3 2012-02-10  5895.5  5895.5  5839.9  5852.4  948790200  5852.4

In [22]:
import xlrd

In [24]:
wb = xlrd.open_workbook('FTSE_2012.xlsx')

In [25]:
wb

In [26]:
sheetNames = wb.sheet_names()

In [27]:
sheet = wb.sheet_by_name(sheetNames[0])

In [29]:
excelData = [] # List to hold data
for i in range(sheet.nrows):
    excelData.append(sheet.row_values(i))

In [30]:
excelData

[[40954.0, 5899.9, 5923.8, 5880.6, 5892.2, 801550000.0, 5892.2],
 [40953.0, 5905.7, 5920.6, 5877.2, 5899.9, 832567200.0, 5899.9],
 [40952.0, 5852.4, 5920.1, 5852.4, 5905.7, 643543000.0, 5905.7],
 [40949.0, 5895.5, 5895.5, 5839.9, 5852.4, 948790200.0, 5852.4]]

In [31]:
import openpyxl

In [32]:
wb = openpyxl.load_workbook('FTSE_2012.xlsx')

In [33]:
wb

In [34]:
sheetNames = wb.sheetnames

In [35]:
sheet = wb[sheetNames[0]]

In [36]:
rows = sheet.rows

In [37]:
rows

<generator object Worksheet._cells_by_row at 0x117b4db88>

In [38]:
open_price = [row[1].value for row in rows]

In [39]:
open_price

[5899.9, 5905.7, 5852.4, 5895.5]

### save and export data

In [42]:
import numpy as np

In [44]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y = np.zeros((10,10))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.savez_compressed('test',x,y)

In [49]:
data = np.load('test.npz')

In [54]:
x = data['arr_0']
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
y = data['arr_1']
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
np.savez_compressed('test', x=x, y=y)

In [57]:
data = np.load('test.npz')

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
x = np.random.randn(10)
x

array([-0.5819558 ,  0.88576323,  2.39731442, -0.53817517,  0.77172347,
        2.4767021 ,  0.45225603,  0.08057975,  0.10787889,  0.44395051])

In [69]:
np.savetxt('commas.csv', x, delimiter=',')

In [70]:
xData = np.loadtxt('commas.csv', delimiter=',')

In [71]:
xData

array([-0.5819558 ,  0.88576323,  2.39731442, -0.53817517,  0.77172347,
        2.4767021 ,  0.45225603,  0.08057975,  0.10787889,  0.44395051])