In [1]:
import numpy as np

In [2]:
x = np.array([[1.0,2.0],[3.0,4.0]])
x

array([[1., 2.],
       [3., 4.]])

In [3]:
y = np.array([[5.0,6.0],[7.0,8.0]])
y

array([[5., 6.],
       [7., 8.]])

In [4]:
z = np.concatenate((x,y),axis = 0)
z

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [5]:
z = np.vstack((x,y))
z

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [6]:
z = np.concatenate((x,y),axis = 1)
z

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [7]:
z = np.hstack((x,y))
z

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])