### Logical Indexing

In [1]:
import numpy as np

In [2]:
x = np.arange(-3,3)
x

array([-3, -2, -1,  0,  1,  2])

In [3]:
x < 0

array([ True,  True,  True, False, False, False])

In [4]:
x[x < 0]

array([-3, -2, -1])

In [5]:
x[abs(x) >= 2]

array([-3, -2,  2])

In [6]:
x = np.reshape(np.arange(-8,8), (4,4))
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [7]:
x[x < 0]

array([-8, -7, -6, -5, -4, -3, -2, -1])

In [8]:
cols = np.any(x < -6, 0)
cols

array([ True,  True, False, False])

In [9]:
rows = np.any(x < 0, 1)
rows

array([ True,  True, False, False])

In [10]:
x[np.ix_(cols,rows)] # Upper 2 by 2

array([[-8, -7],
       [-4, -3]])

### mixing logical indexing with slicing

In [11]:
x

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [12]:
sel = sum(x < -1, 0) >= 2
sel

array([ True,  True,  True, False])

In [13]:
x[:,sel] # All rows, sel selects columns

array([[-8, -7, -6],
       [-4, -3, -2],
       [ 0,  1,  2],
       [ 4,  5,  6]])

In [14]:
x[1:3,sel] # Rows 1 and 2, sel selects columns

array([[-4, -3, -2],
       [ 0,  1,  2]])

In [15]:
x[sel,2:] # sel selects rows, columns 2 and 3

array([[-6, -5],
       [-2, -1],
       [ 2,  3]])