### Numerical Indexing

In [1]:
import numpy as np

In [2]:
x = 10 * np.arange(5.0)
x

array([ 0., 10., 20., 30., 40.])

In [3]:
x[[0]] # List with 1 element

array([0.])

In [4]:
x[[0,2,1]] # List

array([ 0., 20., 10.])

In [5]:
select = np.array([4,2,3,1,4,4]) # Array with repetition
x[select]

array([40., 20., 30., 10., 40., 40.])

In [6]:
select = np.array([[4,2],[3,1]]) # 2 by 2 array
x[select]

array([[40., 20.],
       [30., 10.]])

In [7]:
sel = np.array([0.0,1]) # Floating point data

In [8]:
x[sel] # Error

IndexError: arrays used as indices must be of integer (or boolean) type

In [9]:
x[sel.astype(int)] # No error

array([ 0., 10.])

In [10]:
x[0] # Scalar selection, not numerical indexing

0.0

### multidimensional indexing

In [11]:
x = np.reshape(np.arange(10.0), (2,5))
x

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [12]:
sel = np.array([0,1])
x[sel,sel] # 1dim arrays, no broadcasting

array([0., 6.])

In [13]:
x[sel, sel+1]

array([1., 7.])

In [14]:
sel_row = np.array([[0,0],[1,1]])
sel_col = np.array([[0,1],[0,1]])
x[sel_row,sel_col] # 2 by 2, no broadcasting

array([[0., 1.],
       [5., 6.]])

In [15]:
sel_row = np.array([[0],[1]])
sel_col = np.array([[0,1]])
x[sel_row,sel_col] # 2 by 1 and 1 by 2 difference shapes, broadcasted as 2 by 2

array([[0., 1.],
       [5., 6.]])

In [17]:
x[np.ix_([0,1],[1,2,3])]

array([[1., 2., 3.],
       [6., 7., 8.]])

### mixing numerical indexing with scalar selection

In [18]:
sel = np.array([[1],[2]]) # 2 by 1
x[0,sel] # Row 0, elements sel

array([[1.],
       [2.]])

In [19]:
sel_row = np.array([[0],[0]])
x[sel_row,sel] # Identical

array([[1.],
       [2.]])

### mixing numerical indexing with slicing

In [20]:
x[:,[1]] # select entire column

array([[1.],
       [6.]])

In [21]:
x[[1],:] # select entire row

array([[5., 6., 7., 8., 9.]])