### Logical Indexing Functions

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
sel = x <= 3
sel

array([[ True,  True],
       [ True, False]])

### nonzero

In [4]:
indices = np.nonzero(sel)
indices

(array([0, 0, 1]), array([0, 1, 0]))

In [5]:
x[indices]

array([1, 2, 3])

### flatnonzero

In [6]:
np.flatnonzero(sel)

array([0, 1, 2])

In [7]:
x.flat[np.flatnonzero(sel)]

array([1, 2, 3])

### argwhere

In [8]:
x = np.random.randn(3)
x

array([-0.42826256, -1.9840522 ,  0.41873153])

In [9]:
np.argwhere(x<0.6)

array([[0],
       [1],
       [2]])

In [10]:
x = np.random.randn(3,2)
x

array([[ 1.01027196,  0.65000702],
       [ 0.71782886,  0.93650917],
       [ 1.01869931, -1.74278769]])

In [11]:
np.argwhere(x<0)

array([[2, 1]])

In [12]:
np.argwhere(x<1)

array([[0, 1],
       [1, 0],
       [1, 1],
       [2, 1]])

### extract

In [13]:
x = np.random.randn(3)
x

array([ 0.08945766, -1.37150244,  1.30251446])

In [14]:
np.extract(x<0, x)

array([-1.37150244])

In [15]:
x = np.random.randn(3,2)
x

array([[-0.21227683, -0.89538332],
       [ 0.34038451,  0.46959422],
       [ 0.07815902, -0.13551525]])

In [16]:
np.extract(x>0, x)

array([0.34038451, 0.46959422, 0.07815902])