### Sort, Max (and Min)

In [1]:
import numpy as np

In [2]:
x = np.random.randn(4,2)
x

array([[-0.77525452,  0.69521194],
       [-1.40780708, -0.30342323],
       [ 2.10150559, -0.59897471],
       [ 1.14633149,  0.62733773]])

In [3]:
np.sort(x, axis=0) # sort down columns, min to max

array([[-1.40780708, -0.59897471],
       [-0.77525452, -0.30342323],
       [ 1.14633149,  0.62733773],
       [ 2.10150559,  0.69521194]])

In [4]:
np.sort(x, axis=1) # sort across rows, min to max

array([[-0.77525452,  0.69521194],
       [-1.40780708, -0.30342323],
       [-0.59897471,  2.10150559],
       [ 0.62733773,  1.14633149]])

In [5]:
np.sort(x, axis=None) # sort all

array([-1.40780708, -0.77525452, -0.59897471, -0.30342323,  0.62733773,
        0.69521194,  1.14633149,  2.10150559])

In [6]:
x = np.random.randn(3)
x

array([1.08724902, 2.08341156, 0.34751713])

In [7]:
np.sort(x) # does not change x

array([0.34751713, 1.08724902, 2.08341156])

In [8]:
x.sort() # inplace, changes x
x

array([0.34751713, 1.08724902, 2.08341156])

In [9]:
x = np.random.randn(3,4)
x

array([[-1.93587187, -0.0044167 ,  1.2584169 ,  0.20644008],
       [-1.99315589, -0.00936203, -0.96835125,  0.17091146],
       [ 0.29601887, -0.06923953,  0.19328288, -0.10885103]])

In [10]:
np.amax(x)

1.2584168975955523

In [11]:
x.max()

1.2584168975955523

In [12]:
x.max(0) # max of each column

array([ 0.29601887, -0.0044167 ,  1.2584169 ,  0.20644008])

In [13]:
x.max(1) # max of each row

array([1.2584169 , 0.17091146, 0.29601887])

In [14]:
x = np.random.randn(4)
x

array([ 1.28177891,  0.07273568,  1.42682291, -0.92239402])

In [15]:
y = np.random.randn(4)
y

array([ 0.17584467, -1.08335012,  0.37389251,  1.26626373])

In [16]:
np.maximum(x,y)

array([1.28177891, 0.07273568, 1.42682291, 1.26626373])