### Mathematics

In [1]:
import numpy as np

In [2]:
x = np.random.randn(3,4)
x

array([[ 1.8417282 ,  2.30174612, -0.72129582,  0.13124598],
       [ 0.60723425, -0.85029153,  0.64279795,  0.89790825],
       [-0.27057116,  0.59806216,  0.59711939,  0.40163161]])

In [3]:
np.sum(x) # sum all elements

6.177315391534876

In [4]:
np.sum(x, 0) # sum columns, 4 elements

array([2.17839128, 2.04951675, 0.51862151, 1.43078584])

In [5]:
np.cumsum(x,0) # cumulative sum of columns

array([[ 1.8417282 ,  2.30174612, -0.72129582,  0.13124598],
       [ 2.44896245,  1.4514546 , -0.07849787,  1.02915423],
       [ 2.17839128,  2.04951675,  0.51862151,  1.43078584]])

In [6]:
np.sum(x, 1) # sum rows, 3 elements

array([3.55342448, 1.29764892, 1.32624199])

In [7]:
np.cumsum(x, 1) # cumulative sum of rows

array([[ 1.8417282 ,  4.14347433,  3.42217851,  3.55342448],
       [ 0.60723425, -0.24305728,  0.39974066,  1.29764892],
       [-0.27057116,  0.32749099,  0.92461038,  1.32624199]])

In [8]:
np.diff(x) # Same as diff(x,1)

array([[ 4.60017920e-01, -3.02304194e+00,  8.52541798e-01],
       [-1.45752577e+00,  1.49308947e+00,  2.55110307e-01],
       [ 8.68633324e-01, -9.42774381e-04, -1.95487775e-01]])

In [9]:
np.diff(x, axis=0)

array([[-1.23449396, -3.15203765,  1.36409377,  0.76666228],
       [-0.87780541,  1.44835369, -0.04567856, -0.49627664]])