### Rounding

In [1]:
import numpy as np

In [2]:
x = np.random.randn(3)
x

array([-0.75929805, -0.55232929, -0.81645215])


### rounding using around

In [3]:
np.around(x)

array([-1., -1., -1.])

In [4]:
np.around(x,2)

array([-0.76, -0.55, -0.82])


### rounding using floor

In [5]:
np.floor(x)

array([-1., -1., -1.])


### rounding using ceil

In [6]:
np.ceil(x)

array([-0., -0., -0.])