### Mathematics

In [4]:
import numpy as np

In [6]:
x = np.random.randn(3,4)
x

array([[-0.94221386, -0.24790466, -2.38474856, -0.54577375],
       [-0.48711344, -1.12745378,  0.62148821, -1.20778957],
       [ 0.44135777, -2.20292263, -1.23977465,  0.81085613]])

In [11]:
np.sum(x) # sum all elements

-8.511992785272955

In [12]:
np.sum(x, 0) # sum columns, 4 elements

array([-0.98796953, -3.57828107, -3.003035  , -0.94270718])

In [16]:
np.cumsum(x,0) # cumulative sum of columns

array([[-0.94221386, -0.24790466, -2.38474856, -0.54577375],
       [-1.42932731, -1.37535844, -1.76326035, -1.75356331],
       [-0.98796953, -3.57828107, -3.003035  , -0.94270718]])

In [13]:
np.sum(x, 1) # sum rows, 3 elements

array([-4.12064083, -2.20086859, -2.19048337])

In [18]:
np.cumsum(x, 1) # cumulative sum of rows

array([[-0.94221386, -1.19011852, -3.57486708, -4.12064083],
       [-0.48711344, -1.61456723, -0.99307902, -2.20086859],
       [ 0.44135777, -1.76156486, -3.00133951, -2.19048337]])

In [20]:
np.diff(x) # Same as diff(x,1)

array([[ 0.6943092 , -2.1368439 ,  1.83897481],
       [-0.64034034,  1.74894199, -1.82927777],
       [-2.6442804 ,  0.96314798,  2.05063078]])

In [22]:
np.diff(x, axis=0)

array([[ 0.45510042, -0.87954912,  3.00623677, -0.66201582],
       [ 0.92847122, -1.07546885, -1.86126285,  2.0186457 ]])