In [1]:
import numpy as np


### linspace function

In [2]:
x = np.linspace(0, 10, 11)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


### logspace function

In [3]:
x = np.logspace(0, 10, 11)
x

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])


### arange function

In [4]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
x = np.arange(11.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
x = np.arange(4, 10, 1.5)
x

array([4. , 5.5, 7. , 8.5])


### meshgrid function

In [7]:
x = np.arange(5)
y = np.arange (3)
X,Y = np.meshgrid(x,y)

In [8]:
X

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [9]:
Y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])


### make array "row" using r_

In [10]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.r_[0:10:.5]

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [12]:
np.r_[0:10:11j]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


### make array "column" using c_

In [13]:
np.c_[0:5:2]

array([[0],
       [2],
       [4]])


### select array elements using ix_

In [14]:
x = np.reshape(np.arange(25.0),(5,5))
x

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [15]:
x[np.ix_([2,3],[0,1,2])] # Rows 2 & 3, cols 0, 1 and 2

array([[10., 11., 12.],
       [15., 16., 17.]])

In [16]:
x[2:4,:3] # Same, standard slice

array([[10., 11., 12.],
       [15., 16., 17.]])

In [17]:
x[np.ix_([0,3],[0,1,4])] # No slice equiv

array([[ 0.,  1.,  4.],
       [15., 16., 19.]])


### make array using mgrid

In [18]:
np.mgrid[0:3,0:2:.5]

array([[[0. , 0. , 0. , 0. ],
        [1. , 1. , 1. , 1. ],
        [2. , 2. , 2. , 2. ]],

       [[0. , 0.5, 1. , 1.5],
        [0. , 0.5, 1. , 1.5],
        [0. , 0.5, 1. , 1.5]]])

In [19]:
np.mgrid[0:3:3j,0:2:5j]

array([[[0. , 0. , 0. , 0. , 0. ],
        [1.5, 1.5, 1.5, 1.5, 1.5],
        [3. , 3. , 3. , 3. , 3. ]],

       [[0. , 0.5, 1. , 1.5, 2. ],
        [0. , 0.5, 1. , 1.5, 2. ],
        [0. , 0.5, 1. , 1.5, 2. ]]])


### make array using ogrid

In [20]:
np.ogrid[0:3,0:2:.5]

[array([[0.],
        [1.],
        [2.]]), array([[0. , 0.5, 1. , 1.5]])]

In [21]:
np.ogrid[0:3:3j,0:2:5j]

[array([[0. ],
        [1.5],
        [3. ]]), array([[0. , 0.5, 1. , 1.5, 2. ]])]