### Set Functions

In [1]:
import numpy as np


### unique

In [2]:
x = np.repeat(np.random.randn(3),(2))
x

array([-1.93347263, -1.93347263,  0.39639125,  0.39639125,  0.31517731,
        0.31517731])

In [3]:
np.unique(x)

array([-1.93347263,  0.31517731,  0.39639125])

In [4]:
y,ind = np.unique(x, True)
ind

array([0, 4, 2])

In [5]:
x.flat[ind]

array([-1.93347263,  0.31517731,  0.39639125])


### in1d

In [6]:
x = np.arange(10.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
y = np.arange(5.0,15.0)
y

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [8]:
np.in1d(x,y)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])


### intersect1d

In [9]:
np.intersect1d(x,y)

array([5., 6., 7., 8., 9.])


### union1d

In [10]:
np.union1d(x,y)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])


### setdiff1d

In [11]:
np.setdiff1d(x,y)

array([0., 1., 2., 3., 4.])


### setxor1d

In [12]:
np.setxor1d(x,y)

array([ 0.,  1.,  2.,  3.,  4., 10., 11., 12., 13., 14.])