### Logical, is*

In [1]:
import numpy as np

In [2]:
x = np.array([4,np.pi,np.inf,np.inf/np.inf])
x

array([4.        , 3.14159265,        inf,        nan])

In [3]:
np.isnan(x)

array([False, False, False,  True])

In [4]:
np.isinf(x)

array([False, False,  True, False])

In [5]:
np.isfinite(x)

array([ True,  True, False, False])