### Logical, any and allclose

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
y = x <= 2
y

array([[ True,  True],
       [False, False]])

### any

In [4]:
np.any(y) # any value "True"

True

In [5]:
np.any(y,0) # any value "True", column-wise

array([ True,  True])

In [6]:
np.any(y,1) # any value "True", row-wise

array([ True, False])

### allclose

In [7]:
eps = np.finfo(np.float64).eps
eps

2.220446049250313e-16

In [8]:
x = np.random.randn(2)
x

array([1.13796198, 1.52015931])

In [9]:
y = x + eps
y

array([1.13796198, 1.52015931])

In [10]:
x == y

array([False, False])

In [11]:
np.allclose(x,y)

True