### Logical Operators, Basic

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[-3,-4]])
x

array([[ 1,  2],
       [-3, -4]])

In [3]:
x > 0

array([[ True,  True],
       [False, False]])

In [4]:
x == -3

array([[False, False],
       [ True, False]])

In [5]:
y = np.array([1,-1])
y

array([ 1, -1])

In [6]:
x < y # y broadcast to be (2,2)

array([[False, False],
       [ True,  True]])

In [7]:
z = np.array([[1,1],[-1,-1]]) # Same as broadcast y
z

array([[ 1,  1],
       [-1, -1]])

In [8]:
x < z

array([[False, False],
       [ True,  True]])